name: RedstoneVC
description: $description
version: '${version}'

main: pl.redstonefun.redstonevc.RedstoneVC
api-version: '26.2'
load: POSTWORLD

authors: [ Brzechuu ]
website: https://github.com/Brzechuu/RedstoneVC
